entities:
  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato1
    prefab_name: tomato
    pose:
      translation:
        x: 0.2
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
