entities:
  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.15
        y: 0.35
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.45
        y: 0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: yellow_cube1
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.25
        y: 0.5
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
