entities:
  - name: carrot1
    prefab_name: carrot
    pose:
      translation:
        x: 0.4
        y: 0.0
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato1
    prefab_name: tomato
    pose:
      translation:
        x: 0.45
        y: 0.0
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.35
        y: 0.0
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
