entities:
  - name: yellow_cube1
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.5
        y: 0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
