entities:
  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: apple2
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.15
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.3
        y: -0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
