entities:
  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.4
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: apple2
    prefab_name: apple
    pose:
      translation:
        x: 0.3
        y: -0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: apple3
    prefab_name: apple
    pose:
      translation:
        x: 0.5
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: tomato1
    prefab_name: tomato
    pose:
      translation:
        x: 0.4
        y: -0.35
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: tomato2
    prefab_name: tomato
    pose:
      translation:
        x: 0.4
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato3
    prefab_name: tomato
    pose:
      translation:
        x: 0.1
        y: -0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: tomato4
    prefab_name: tomato
    pose:
      translation:
        x: 0.5
        y: 0.35
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.6
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube2
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.35
        y: 0.30
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
