entities:
  - name: carrot1
    prefab_name: carrot
    pose:
      translation:
        x: 0.0
        y: -0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: carrot2
    prefab_name: carrot
    pose:
      translation:
        x: 0.05
        y: -0.2
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: carrot3
    prefab_name: carrot
    pose:
      translation:
        x: 0.05
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: apple1
    prefab_name: apple
    pose:
      translation:
        x: 0.2
        y: -0.1
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: blue_cube1
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.4
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: red_cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.45
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: yellow_cube1
    prefab_name: yellow_cube
    pose:
      translation:
        x: 0.5
        y: 0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: corn1
    prefab_name: corn
    pose:
      translation:
        x: 0.6
        y: 0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: blue_cube2
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.4
        y: 0.45
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
