entities:
  - name: cube1
    prefab_name: red_cube
    pose:
      translation:
        x: 0.5
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: cube2
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.4
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: cube3
    prefab_name: red_cube
    pose:
      translation:
        x: 0.5
        y: -0.3
        z: 0.15
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: cube4
    prefab_name: red_cube
    pose:
      translation:
        x: 0.5
        y: -0.3
        z: 0.25
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: cube5
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.3
        y: -0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

  - name: cube6
    prefab_name: blue_cube
    pose:
      translation:
        x: 0.3
        y: -0.3
        z: 0.15
      rotation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
