entities:
  - name: carrot1
    prefab_name: carrot
    pose:
      translation:
        x: 0.5
        y: -0.3
        z: 0.05
      rotation:
        x: 0.5
        y: 0.0
        z: 0.0
        w: 0.0

  - name: carrot2
    prefab_name: carrot
    pose:
      translation:
        x: 0.5
        y: 0.3
        z: 0.05
      rotation:
        x: 0.0
        y: 0.0
        z: 0.7
        w: 0.0
  - name: carrot3
    prefab_name: carrot
    pose:
      translation:
        x: 0.5
        y: 0.4
        z: 0.05
      rotation:
        x: 0.2
        y: 0.0
        z: 0.0
        w: 0.4

  - name: carrot4
    prefab_name: carrot
    pose:
      translation:
        x: 0.5
        y: -0.4
        z: 0.05
      rotation:
        x: 0.0
        y: 0.9
        z: 0.0
        w: 0.5
