name: build mkdocs

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  build-mkdocs:
    if: github.event.pull_request.draft == false

    runs-on:
      - ubuntu-24.04
    container:
      image: python:3.12-slim

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Cache uv and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install python dependencies
        run: uv sync --frozen --all-groups

      - name: Build docs
        shell: bash
        run: |
          uv run mkdocs build --strict
