name: publish mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-mkdocs:
    runs-on:
      - ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Cache Poetry and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1

      - name: Install python dependencies
        run: poetry install --with docs

      - name: Build and Deploy
        shell: bash
        run: |
          poetry run mkdocs gh-deploy --force
