name: publish mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-mkdocs:
    runs-on:
      - ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Cache uv and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install python dependencies
        run: uv sync --group docs

      - name: Install rai packages
        run: uv run pip install src/rai_core src/rai_sim src/rai_bench src/rai_s2s --no-deps

      - name: Build and Deploy
        shell: bash
        run: |
          uv run mkdocs gh-deploy --force
