name: Poetry Update

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 1"

jobs:
  upgrade-dependencies:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: fuzzylabs/gha-poetry-update@v1
        with:
          python-version: 3.12
