name: Poetry Update

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 1"

jobs:
  upgrade-dependencies:
    runs-on:
      - self-hosted
      - robo-pc-066

    container:
      image: ubuntu:24.04

    steps:
      - name: Clean up build space
        run: |
          ls -la $GITHUB_WORKSPACE
          rm -rf $GITHUB_WORKSPACE/* || true
          rm -rf $GITHUB_WORKSPACE/.??* || true
          ls -la $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE/../../_temp/_github_home
          rm -rf $GITHUB_WORKSPACE/../../_temp/_github_home/* || true
          rm -rf $GITHUB_WORKSPACE/../../_temp/_github_home/.??* || true
          ls -la $GITHUB_WORKSPACE/../../_temp/_github_home

      - uses: fuzzylabs/gha-poetry-update@v1
        with:
          python-version: 3.12
