name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on:
      - self-hosted

    container:
      image: osrf/ros:humble-desktop-full

    steps:

      - name: Install pre-commit
        run: |
          apt update && apt install -y python3-pip shellcheck
          python3 -m pip install pre-commit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ROS 2 package dependencies
        shell: bash
        run: |
          vcs import . < ros_deps.repos

      - run: |
          git config --global --add safe.directory /__w/rai/rai
      - run: |
          git branch
          ls .git

      - shell: bash
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure --color=always
