name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Install vcs
        shell: bash
        run: |
          echo 'Etc/UTC' > /etc/timezone
          ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
          apt update && apt install -y curl software-properties-common
          add-apt-repository -y universe
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
          apt update && apt install -y python3-vcstool

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install ROS 2 package dependencies
        shell: bash
        run: |
          vcs import . < ros_deps.repos

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"
