name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on:
      - self-hosted

    container:
      image: osrf/ros:humble-desktop-full

    steps:
      - name: Install pre-commit
        run: |
          apt update && apt install -y python3-pip shellcheck python-is-python3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
           git config --global --add safe.directory /__w/rai/rai

      - name: Import ros2 dependencies
        shell: bash
        run: |
          vcs import . < ros_deps.repos

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"
