name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on:
      - self-hosted
      - robo-pc-066

    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"
