name: Pre-commit Checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on:
      - self-hosted

    container:
      image: osrf/ros:humble-desktop-full

    steps:
      - name: Fix ROS 2 keys # TODO: remove this once https://github.com/docker-library/official-images/pull/19162 is merged
        run: |
          rm /etc/apt/sources.list.d/ros2-latest.list
          rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg
          apt-get update
          apt-get install -y ca-certificates curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
          curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
          && apt-get update \
          && apt-get install /tmp/ros2-apt-source.deb \
          && rm -f /tmp/ros2-apt-source.deb

      - name: Install pre-commit
        run: |
          apt update && apt install -y python3-pip shellcheck python-is-python3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
           git config --global --add safe.directory /__w/rai/rai

      - name: Import ros2 dependencies
        shell: bash
        run: |
          vcs import . < ros_deps.repos

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"
