name: "Require rai_core pyproject change when code changes"
on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'src/rai_core/**'
      - 'src/rai_core/pyproject.toml'

jobs:
  check-rai-core-pyproject:
    name: Require version bump if rai_core changed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tomli
        run: |
          pip install tomli

      - name: Verify rai_core pyproject changed
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail

          echo "Base: ${BASE_SHA}"
          echo "Head: ${HEAD_SHA}"

          # List changed files between base and head
          CHANGED_FILES=$(git diff --name-only "${BASE_SHA}" "${HEAD_SHA}")
          echo "Changed files:\n${CHANGED_FILES}"

          # Detect changes within src/rai_core/
          if ! printf '%s\n' "${CHANGED_FILES}" | grep -E '^src/rai_core/' >/dev/null 2>&1; then
            echo "No changes detected in src/rai_core. Skipping check."
            exit 0
          fi

          echo "Changes detected in src/rai_core. Verifying src/rai_core/pyproject.toml is updated..."

          # Ensure src/rai_core/pyproject.toml is among changed files
          if printf '%s\n' "${CHANGED_FILES}" | grep -xq 'src/rai_core/pyproject.toml'; then
            echo "Detected change in src/rai_core/pyproject.toml."
            echo "Checking version bump with Python..."
            BASE_VERSION=$(git show "${BASE_SHA}:src/rai_core/pyproject.toml" | python -c "import tomli, sys; print(tomli.load(sys.stdin)['project']['version'])")
            HEAD_VERSION=$(git show "${HEAD_SHA}:src/rai_core/pyproject.toml" | python -c "import tomli, sys; print(tomli.load(sys.stdin)['project']['version'])")

            echo "Base version: ${BASE_VERSION:-<not found>}"
            echo "Head version: ${HEAD_VERSION:-<not found>}"

            if [ "${BASE_VERSION}" = "${HEAD_VERSION}" ]; then
              echo "ERROR: pyproject.toml modified but version was not bumped."
              exit 1
            fi

            echo "✅ Version bump detected: ${BASE_VERSION} -> ${HEAD_VERSION}"
            exit 0
          fi

          echo "ERROR: Files in src/rai_core changed but src/rai_core/pyproject.toml was not modified in this PR."
          echo "Update the version in the pyproject.toml file and commit the changes according to changes with respect to Semantic Versioning."
          echo "Bump patch if a bug fix is introduced, minor if a feature is added, and major if a breaking change is added."
          echo "Disregard the version bump only if you know what you are doing."
          exit 1
