name: File Diff

on:
  pull_request:
    branches:
      - main

jobs:
  file-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get file contents from BASE and HEAD
        id: file_diff
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          FILE_PATH="src/rai_core/pyproject.toml"

          # Get BASE version
          git show $BASE_SHA:$FILE_PATH > base.txt || echo "BASE file not found"
          
          # Get HEAD version
          git show $HEAD_SHA:$FILE_PATH > head.txt || echo "HEAD file not found"

          # Export as outputs
          {
            echo "base<<EOF"
            cat base.txt
            echo "EOF"
            echo "head<<EOF"
            cat head.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Compare version lines
        run: |
          BASE_VERSION=$(grep '^version =' base.txt || echo "MISSING")
          HEAD_VERSION=$(grep '^version =' head.txt || echo "MISSING")

          echo "BASE: $BASE_VERSION"
          echo "HEAD: $HEAD_VERSION"

          if [ "$BASE_VERSION" = "$HEAD_VERSION" ]; then
            echo "❌ Version has not changed, failing CI"
            exit 1
          else
            echo "✅ Version changed, passing CI"
          fi
