name: ruff checks

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: chartboost/ruff-action@v1
